Parameters:
  SubnetId:
    Type: String
    Default: subnet-027782e808cd8ba6a
  SecurityGroupId:
    Type: String
    Default: sg-06edb86084003f733
  ImageId:
    Type: String
    Default: ami-06c68f701d8090592

Resources:
  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref ImageId
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
      - !Ref SecurityGroupId